name: flutter_advanced_template_v2
description: "An advanced Flutter project template with many features and tools."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.5.0

dev_dependencies:
  melos: ^7.1.0
  build_runner: ^2.7.0