name: log_manager
description: The log manager handles logging for the application.
version: 0.0.1

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4
