name: navigation_manager
description: A module to manage the navigation of the app.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Models
  equatable: ^2.0.5

  # Go router
  go_router: ^14.3.0

  # Log Manager
  log_manager:
    path: ../log_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4
