name: permission_manager
description: A module to manage permissions for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Permission Handler
  permission_handler: ^12.0.1

  # Log Manager
  log_manager:
    path: ../log_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
