name: auth_manager
description: A module to manage authentication for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Auth
  firebase_auth: ^6.1.2

  # Logging
  log_manager:
    path: ../log_manager

  # Social Login
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # Crypto
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4

