name: cloud_storage_manager
description: A platform-independent module to manage cloud-based file storage operations for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Storage
  firebase_storage: ^12.2.0

  # Path Provider
  path_provider: ^2.1.4

  # Logging
  log_manager:
    path: ../log_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  mocktail: ^1.0.4

  path_provider_platform_interface: any
  plugin_platform_interface: any
