name: connectivity_manager
description: A module to manage connectivity services for Flutter apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  connectivity_plus: ^6.1.0
  rxdart: ^0.28.0

  log_manager:
    path: ../log_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
